<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_our mission</name>
   <tag></tag>
   <elementGuidId>dcd7d52b-3cfb-4ad2-9dac-4c0e9e8eb6fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mui-p-85489-T-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-p-85489-T-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce8fa093-22a3-454f-94bb-13d7ae284d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1q2h7u5</value>
      <webElementGuid>05c8b96f-b8f3-4d08-8db5-246c8bfeafc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>62753857-5423-460a-a78e-5c0b7b172ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10d62580-0b5a-4438-8f2a-a772e1b4f72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>64302f0c-74bd-4bb3-b1bd-ae4dcdcc61ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11163aa9-f6f9-47f2-a808-a20cf220f0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-p-85489-P-2</value>
      <webElementGuid>bd47aa1c-0b91-4aa1-9b30-1fb6f26505ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-p-85489-T-2</value>
      <webElementGuid>ec5f56be-0622-4758-b5e9-8c60a6cc9b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>our mission</value>
      <webElementGuid>a8f288cc-9806-47aa-b050-c4cde57b1d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-p-85489-T-2&quot;)</value>
      <webElementGuid>aa45becd-a39e-4412-8f9f-a545aaccace2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-p-85489-T-2']</value>
      <webElementGuid>06d08f4c-f4c7-457f-b416-eca434de2689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[5]/div/div/div/div/div/button[2]</value>
      <webElementGuid>4618fc78-a4d0-4b4e-aaf3-0a25ba1d1af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='about us'])[1]/following::button[1]</value>
      <webElementGuid>21af39e8-1218-4eca-bf18-dc87013ce261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='are'])[1]/following::button[2]</value>
      <webElementGuid>ad631c97-026a-4ce9-9bc1-09556371390d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TECHSEED'])[3]/preceding::button[1]</value>
      <webElementGuid>08f89b38-c63c-4002-a7a5-26139429dfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='secure'])[1]/preceding::button[1]</value>
      <webElementGuid>9b43271b-1c06-497c-b46c-e4ff0ce35b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='our mission']/parent::*</value>
      <webElementGuid>f18eb11c-6a55-4541-94bb-8e8f49a7713c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>430639a5-0a27-402d-8769-6bf8db61ea3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mui-p-85489-T-2' and (text() = 'our mission' or . = 'our mission')]</value>
      <webElementGuid>f92249df-12aa-485f-a98d-6eebeb182107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
